import React from "react";
import Head from "next/head";
import Properties from "@/components/TrendEdit";
import Hero from "@/components/hero";
import RealEstateMarkets from "@/components/RealEstateMarkets";


const HomePage = () => {
  return (
    <>
      <Head>
        <title>VEYRANI PRIME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />

        <Properties />

        <RealEstateMarkets />

      </div>
    </>
  );
};

export default HomePage;
